### NUMPY
Numpy is a fundamental library in python for scientific calculations. It provides support for arrays,matrices , along with a collection of mathematical functions to operate on these data structures

In [3]:
import numpy as np

In [6]:
## create array using numpy
## create a 1D array
arr1=np.array([1,2,3,4,5,6,7,8,9])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
(9,)


In [ ]:
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5) # 1 row and 5 columns

array([[1, 2, 3, 4, 5]])

In [10]:
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2)
print(arr2.shape) # 3 rows and 3 columns

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [12]:
arr3=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]]])
print(arr3)
print(arr3.shape) # 3 layers, 3 rows and 3 columns

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
(3, 3, 3)
