### NUMPY
Numpy is a fundamental library in python for scientific calculations. It provides support for arrays,matrices , along with a collection of mathematical functions to operate on these data structures

In [3]:
import numpy as np

In [6]:
## create array using numpy
## create a 1D array
arr1=np.array([1,2,3,4,5,6,7,8,9])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
(9,)


In [ ]:
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5) # 1 row and 5 columns

array([[1, 2, 3, 4, 5]])

In [ ]:
#2D ARRAY
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2)
print(arr2.shape) # 3 rows and 3 columns

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [ ]:
# 3D ARRAY
arr3=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]]])
print(arr3)
print(arr3.shape) # 3 layers, 3 rows and 3 columns

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
(3, 3, 3)


In [15]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [17]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [19]:
## identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
#Attributes of numpy array
arr=np.array([[1,2,3],[4,5,6]])

print('Array:\n',arr)
print('Shape:\n',arr.shape)
print('Size:\n',arr.size)
print('Dimension:\n',arr.ndim)
print('Data type:\n',arr.dtype)
print('Data type of each element:\n',arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Shape:
 (2, 3)
Size:
 6
Dimension:
 2
Data type:
 int64
Data type of each element:
 8


In [26]:
### Numpy Vectorized operations
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])
print("Addition of array:",arr1+arr2) # element wise addition
print("Substraction:",arr1-arr2) # element wise subtraction
print("Multiplication:",arr1*arr2) # element wise multiplication
print("division:",arr1/arr2) # element wise division
print("power:",arr1**3) # element wise exponentiation

Addition of array: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
division: [0.1 0.1 0.1 0.1 0.1]
power: [  1   8  27  64 125]


In [28]:
## universal functions in numpy
arr=np.array([1,2,3,4,5])
## square root of each element
print("Square Root:", np.sqrt(arr))
print("Exponential:", np.exp(arr))
print("Sine", np.sin(arr))
print("Cosine", np.cos(arr))
print("Logarithm", np.log(arr))

Square Root: [1.         1.41421356 1.73205081 2.         2.23606798]
Exponential: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Sine [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
Cosine [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
Logarithm [0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [ ]:
## Universal functions in numpy are functions that operate element wise on an array. They are also known as ufuncs. They are implemented in C and are very fast. They can be used to perform mathematical operations on arrays without the need for explicit loops.


In [30]:
## Array slicing and indexing
arr=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print("Array: \n",arr)

Array: 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [34]:
print("First row first element:", arr[0][0]) # first row first element
print('Second row third element:',arr[1][2]) # second row third element
print('Last row last element:',arr[2][4]) # last row last element

First row first element: 1
Second row third element: 8
Last row last element: 15


In [36]:
# print 9 10 14 15
print(arr[1:,3:])

[[ 9 10]
 [14 15]]


In [41]:
# print 4 5 9 10
print(arr[0:2,3:])

[[ 4  5]
 [ 9 10]]


In [44]:
## print 7 8 9 12 13 14
print(arr[1:,1:4])

[[ 7  8  9]
 [12 13 14]]


In [45]:
##  modify array elements
arr[0][1]=100
print(arr)

[[  1 100   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]]


In [46]:
### Statistical Conceot - Normalization
## to have a mean of 0 and standard deviation of 1
data=np.array([1,2,3,4,5])
mean = np.mean(data)
stadev= np.std(data)

## Normaliztion
normalization= (data-mean)/stadev
print("Normalized Data:", normalization)

Normalized Data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [48]:
### Mean Median Mode Standard deviatoion
data1=np.array([1,2,3,4,5,6,7,8,9,10])

#mean
mean=np.mean(data1)
print("Mean:", mean)

#median
median=np.median(data1)
print("Median:",median)

#standard deviation
std=np.std(data1)
print("Standard deviation:", std)

#variance
var=np.var(data1)
print("variance:",var)

Mean: 5.5
Median: 5.5
Standard deviation: 2.8722813232690143
variance: 8.25


In [ ]:
### Logical operations

data3= np.array([1,2,3,4,5,6,7,8,9,10])

data3[data3>5]


array([ 6,  7,  8,  9, 10])

In [52]:
data3[(data3>5)&(data3 <8)] 

array([6, 7])